# Configurações de otimização para reduzir tamanho do executável
[profile.release]
opt-level = "z"          # Otimizar para tamanho
lto = true               # Link Time Optimization
codegen-units = 1        # Melhor otimização
panic = "abort"          # Reduzir tamanho removendo unwinding
strip = true             # Remover símbolos de debug

# Para compilar com tamanho mínimo:
# cargo build --release

# O executável final terá o texconv.exe embutido e será um arquivo único
# de aproximadamente 4-6MB que funciona sem dependências externas.
